language: c
addons:
  apt:
    packages:
    - ocaml-nox
    - ocaml-findlib

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y frei0r-plugins-dev

script: ./bootstrap && ./configure && make
